# Generated by Django 2.1.7 on 2019-02-27 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_industry', models.CharField(choices=[('SW', 'Software Driven'), ('HW', 'Hardware Driven')], default='SW', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_role', models.CharField(max_length=200)),
                ('job_location', models.CharField(max_length=10)),
                ('job_description', models.TextField()),
                ('job_opened', models.DateTimeField(verbose_name='Date inserted to DB')),
                ('job_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Company')),
            ],
        ),
    ]
