# Generated by Django 2.1.7 on 2019-03-02 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190301_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_link',
            field=models.URLField(default='www.default.com', max_length=128),
            preserve_default=False,
        ),
    ]
