# Generated by Django 2.1.7 on 2019-03-02 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_job_job_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_industry',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_opened',
        ),
    ]
