# Generated by Django 2.1.7 on 2019-03-02 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190302_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('PT', 'Part-Time'), ('FT', 'Full-Time')], default='FT', max_length=2),
        ),
    ]
